# Generated by Django 3.0.3 on 2020-03-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='F1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('block', models.CharField(blank=True, max_length=25, null=True)),
                ('no_enrolled', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tot_elgb_wghd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tot_elgb_hght', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('no_wt', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('no_ht', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('no_wt_ht', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('weightp', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('heightp', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('heightweightp', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'f1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='F2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('block', models.CharField(blank=True, max_length=25, null=True)),
                ('wasting', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('stunting', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('underweight', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('lbw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'f2',
                'managed': False,
            },
        ),
    ]
