# Generated by Django 3.0.3 on 2020-03-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='F3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('block', models.CharField(blank=True, max_length=15, null=True)),
                ('project', models.CharField(blank=True, max_length=25, null=True)),
                ('mdrtly_stntd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('svrly_stntd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('svr_wstg', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mdrtly_wstd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('svrly_uw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mdrtly_uw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nb_lbw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wasting', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('stunting', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('underweight', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('lbw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'f3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='F4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('mdrtly_stntd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('svrly_stntd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('svrly_wstd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mdrtly_wstd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('svrly_uw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('mdrtly_uw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('nb_lbw', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wstd_chld', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('stntd_chld', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('uw_chld', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wasting_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('stunting_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('underweight_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('low_birth_weight_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_chld_bf_at_birth', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_chld_excly_bf', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_chld_rcvg_cf_wid_adq_dt_dvsty', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_chld_cf_wid_adq_dt_qnty', models.CharField(blank=True, max_length=10, null=True)),
                ('per_no_chld_cf_wid_appr_hndwhg_bfr_fdg', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_anwmic_wmn', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_4_anc_vst_dlvry', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_wmn_etg_xtr_ml_drng_prgncy', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_wmn_rstg_drg_prgncy', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_trmstr_3wmn_cnsld_imdtbf', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_child_6to8mnths_intd_cf', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_child_6to24mnths_intd_cf', models.CharField(blank=True, max_length=10, null=True)),
                ('prnt_child_1yr_cmpltd_immunzt', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'f4',
                'managed': False,
            },
        ),
    ]
