# Generated by Django 3.0.3 on 2020-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0006_auto_20200404_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='F1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_n', models.CharField(blank=True, max_length=10, null=True)),
                ('district_n', models.CharField(blank=True, max_length=25, null=True)),
                ('block_n', models.CharField(blank=True, max_length=25, null=True)),
                ('no_enrolled', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tot_elgb_wghd', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tot_elgb_hght', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('no_wt', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('no_ht', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('no_wt_ht', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wt_percent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ht_percent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ht_wt_percent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'f1',
                'managed': False,
            },
        ),
    ]
