# Generated by Django 3.0.3 on 2020-04-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0009_f4'),
    ]

    operations = [
        migrations.CreateModel(
            name='F3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_n', models.CharField(blank=True, max_length=10, null=True)),
                ('district_n', models.CharField(blank=True, max_length=25, null=True)),
                ('block_n', models.CharField(blank=True, max_length=25, null=True)),
                ('project_n', models.CharField(blank=True, max_length=25, null=True)),
                ('stunting_percent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wasting_percent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('underweight_percent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('low_birth_weight_percent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('per_no_enrld', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'f3',
                'managed': False,
            },
        ),
    ]
