# Generated by Django 3.0.3 on 2020-04-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0013_f7iycfaw_f7iycfblock_f7iycfbt_f7iycfproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F7IycfAw',
        ),
        migrations.DeleteModel(
            name='F7IycfBlock',
        ),
        migrations.DeleteModel(
            name='F7IycfBt',
        ),
        migrations.DeleteModel(
            name='F7IycfProject',
        ),
    ]
