# Generated by Django 3.0.3 on 2020-04-16 01:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0016_f8pwawc_f8pwbeat_f8pwblock_f8pwproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtShapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('block', models.CharField(blank=True, max_length=25, null=True)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'dt_shapefile',
                'managed': False,
            },
        ),
    ]
