# Generated by Django 3.0.3 on 2020-04-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0017_dtshapefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F8PwAwc',
        ),
        migrations.DeleteModel(
            name='F8PwBeat',
        ),
        migrations.DeleteModel(
            name='F8PwBlock',
        ),
        migrations.DeleteModel(
            name='F8PwProject',
        ),
    ]
