# Generated by Django 3.0.3 on 2020-04-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0019_f8pwawc_f8pwbeat_f8pwblock_f8pwproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsoChildNdj',
        ),
        migrations.DeleteModel(
            name='DtShapefile',
        ),
    ]
