# Generated by Django 3.0.3 on 2020-04-21 13:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0020_auto_20200416_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictBlockWiseGeojson',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.CharField(blank=True, max_length=15, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('district', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'district_block_wise_geojson',
                'managed': False,
            },
        ),
    ]
