# Generated by Django 3.0.3 on 2020-04-25 02:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0021_districtblockwisegeojson'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictAwcGeojson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(blank=True, max_length=15, null=True)),
                ('beat', models.CharField(blank=True, max_length=100, null=True)),
                ('beat_code', models.IntegerField(blank=True, null=True)),
                ('beat_withc', models.CharField(blank=True, max_length=100, null=True)),
                ('awc_with_c', models.CharField(blank=True, max_length=100, null=True)),
                ('awc', models.CharField(blank=True, max_length=100, null=True)),
                ('awc_code', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('district', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'district_awc_geojson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictBeatWiseGeojson',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('beat_na', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.CharField(blank=True, max_length=20, null=True)),
                ('block', models.CharField(blank=True, max_length=15, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('district', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'district_beat_wise_geojson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictProjectWiseGeojson',
            fields=[
                ('project', models.CharField(blank=True, max_length=20, null=True)),
                ('block', models.CharField(blank=True, max_length=15, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('district', models.CharField(blank=True, max_length=15, null=True)),
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'district_project_wise_geojson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FtRadar2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_n', models.CharField(blank=True, max_length=10, null=True)),
                ('district_n', models.CharField(blank=True, max_length=20, null=True)),
                ('block_n', models.CharField(blank=True, max_length=20, null=True)),
                ('project_n', models.CharField(blank=True, max_length=25, null=True)),
                ('prnt_aneamic_free_wmn', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prnt_child_1yr_cmpltd_immunzt', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prnt_chld_bf_at_birth', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prnt_chld_excly_bf', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prnt_chld_6to8_intd_cf', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prnt_chld_intd_cf', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('norm_anemic_free_wmn', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('norm_chld_bf_at_birth', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('norm_child_immunization', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('norm_chld_excly_bf', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('norm_chld_6to8_intd_cf', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('norm_chld_intd_cf', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('norm_chld_bf', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('norm_chld_cf', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'ft_radar2',
                'managed': False,
            },
        ),
    ]
