# Generated by Django 3.0.3 on 2020-04-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0022_districtawcgeojson_districtbeatwisegeojson_districtprojectwisegeojson_ftradar2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F3',
        ),
    ]
