# Generated by Django 3.0.3 on 2020-04-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0024_f3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F4',
        ),
    ]
