# Generated by Django 3.0.3 on 2020-04-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0026_f4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F4',
        ),
    ]
