# Generated by Django 3.0.3 on 2020-05-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0028_f4'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'quarter_select',
                'managed': False,
            },
        ),
    ]
