# Generated by Django 3.0.3 on 2020-06-16 12:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyd_dashboard', '0029_quarterselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictVillagewiseGeojson',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.CharField(blank=True, max_length=25, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('block', models.CharField(blank=True, max_length=25, null=True)),
                ('beat_na', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'district_villagewise_geojson',
                'managed': False,
            },
        ),
    ]
