# Generated by Django 3.0.3 on 2020-06-01 15:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maha_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MhDtGeojson',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mh_dt_geojson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MhSubdtGeojson',
            fields=[
                ('ogc_fid', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('block', models.CharField(blank=True, max_length=25, null=True)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'mh_subdt_geojson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuarterSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(blank=True, max_length=10, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'quarter_select',
                'managed': False,
            },
        ),
    ]
